apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1-prod 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-prod
  template:
    metadata:
      labels:
        app: app1-prod 
    spec:
      containers:
        - name: app1-prod 
          image: yole0devops0c1.azurecr.io/yoletechdevopsdockercomposenodejsmysql
          ports:
          - containerPort: 8080