apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1-dev 
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-dev
  template:
    metadata:
      labels:
        app: app1-dev
    spec:
      containers:
        - name: app1-dev 
          image: yole0devops0c1.azurecr.io/yoletechdevopsdockercomposenodejsmysql
          ports:
          - containerPort: 8080