apiVersion: v1
kind: Service
metadata:
    name: app1-service-dev
    namespace: dev
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: app1-dev
        namespace: dev